# Generated by Django 4.0.4 on 2022-04-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_products_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='purchese',
            new_name='name',
        ),
        migrations.AddField(
            model_name='products',
            name='currency',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
