# Generated by Django 4.0.4 on 2022-04-26 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_cart_rename_purchese_products_name_products_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='img',
            field=models.FileField(null=b'I01\n', upload_to=''),
            preserve_default=b'I01\n',
        ),
    ]
