# Generated by Django 4.0.4 on 2022-04-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_products_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='currency',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='cart',
            name='name',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(max_length=100, null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AlterField(
            model_name='cart',
            name='amount',
            field=models.CharField(max_length=100, null=b'I01\n'),
        ),
    ]
